fix(ci): use actions v2 for setting up node
node-oauth/node-oauth2-server pull request #117
Opened 2022-01-13 08:21 UTC by jankapunkt

## Summary

This PR is for testing the release workflow in action until it runs through.
No publish will be done, only dry-runs

## Linked issue(s)

#116 #36 

## Involved parts of the project

CI

## Added tests?

they are the tests

## OAuth2 standard

not releated

## Reproduction

not releated

2022-01-13 08:40 UTC, jorenvandeweyer approved these changes, later dismissed

2022-01-13 10:08 UTC, jankapunkt commented
sorry for the email spam on failed workflows but the paths in github actions are really a tricky one....

2022-01-13 10:31 UTC, jankapunkt commented
@jorenvandeweyer  I now forked the express adapter to our org and updated it so we can have integration tests with new releases and see if the express adapter breaks (which it does not right now). Was a big hassle but now it's working. Can you please take a short look at it?

2022-01-13 10:38 UTC, jorenvandeweyer approved these changes, later dismissed

2022-02-01 17:37 UTC, jankapunkt commented
Okay I commented out the `release.yml` for now and will make a manual release, once all merged into 4.2.0 but until then we need first merge this one finally

2022-03-18 07:36 UTC, jankapunkt commented
@Uzlopak @jorenvandeweyer @HappyZombies I need at least one reviewer in order to merge this.

2022-03-18 07:48 UTC, jorenvandeweyer approved these changes

2022-03-18 07:49 UTC, Uzlopak requested changes, later dismissed
We don't have linting check? Maybe should be added in a separate PR?

2022-03-18 07:49 UTC, Uzlopak commented on .github/workflows/codeql-analysis.yml
> +    types: [review_requested, ready_for_review] # only non-draft PR
Interesting. Didn't know this..will probably add this to my projects.

2022-03-18 07:49 UTC, Uzlopak commented on .github/workflows/tests-release.yml
> +        node: [12, 14, 16]
Please add node 17. We got a regression in mongoose few weeks ago, could have been detected earlier if we would have tested also for node17. Better to also add chec for node17 and later node 18 and 19, while dropping node 12 and 17.

2022-03-18 07:49 UTC, Uzlopak commented on .github/workflows/tests-release.yml
> +    - name: check coverage
If we use NYC we can set minimum code coverage and then it already throws an error in the step above.

This is how I do it in a project of mine

https://github.com/cthulhu-node/benchmark.js

2022-03-18 07:49 UTC, Uzlopak commented on .github/workflows/tests-release.yml
> +        node: [12, 14] # TODO get running for node 16
Create follow up issue after merge

2022-03-18 07:49 UTC, Uzlopak commented on .github/workflows/tests.yml
> +    - name: check coverage
The same as above.

2022-03-18 07:49 UTC, Uzlopak commented on .github/workflows/tests-release.yml
> +        node: [12, 14, 16]
It is not a must have...

2022-03-18 07:54 UTC, Uzlopak reviewed
Hey, I don't want to be the blocker. I change my vote to comment. :)

2022-03-18 11:00 UTC, merged

2022-03-18 11:00 UTC, jankapunkt commented
@Uzlopak let's open a new Issue since this can be implemented independently from the next release