Draft: Release 4.2.0
node-oauth/node-oauth2-server pull request #135
Opened 2022-03-18 11:21 UTC by jankapunkt

## Summary

This is an ongoing PR for the release `4.2.0` which will only include fixes and minor features (non-breaking).

## Linked issue(s)

TBD

## Involved parts of the project

TBD

## Added tests?

TBD

## OAuth2 standard

TBD

## Reproduction

TBD

2022-04-15 12:51 UTC, jankapunkt commented
If there are no further PRs to merge into 4.2.0 I will resolve the conflicts and create a new release. Is everybody okay with that? I can also create an rc-release if you first want to test it with your setups.

2022-05-20 10:33 UTC, bmxpiku commented
I am awaiting this :)

2022-05-20 14:05 UTC, Uzlopak commented
Just do it

2022-06-02 20:19 UTC, HappyZombies commented on CHANGELOG.md
> -## 4.1.1
Are we removing the changelog for 4.1.1?

2022-06-03 11:44 UTC, jankapunkt commented
:tada: all conflicts resolved, we should be good to go. One needs to approve. I will create a new GitHub release and publish to NPM

2022-06-04 17:17 UTC, HappyZombies requested changes

2022-06-04 17:17 UTC, HappyZombies commented on package.json
> +  "version": "4.1.0",
Version downgraded by accident here.

2022-06-05 07:02 UTC, jankapunkt commented on package.json
> +  "version": "4.1.0",
I will set 4.2.0, thank you

2022-06-05 12:04 UTC, HappyZombies approved these changes
Code Review Completed

2022-06-06 07:15 UTC, merged